### ISSUE TITLE
Retrieve cached files

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#131]
Add the ability to retrieve one or more, or a folder of cached files from the Files Manager

**Comment by DrSpringy** [comment]
links in with https://github.com/UQ-RCC/ipp/issues/61

**Comment by markendr** [comment]
JS, NC, DG, ND, ME zoom call on 12-Mar-2024:
- User experience issue: long delays reading large files, web page timeouts, multiple retries needed
- ME: Files can be recalled but cache retention period is not transparent (eg. due to other user recalls) 
- JS: Any bunya improvements?
  - DG: expect bunya storage/cache/scratch improvements over wiener will provide significant benefits
- JS requests RCC develop strategy to resolve
  - eg. user file recall capabilities, portal timeouts review
Info added to CRM #230920-000918 - close this issue here

**Comment by ndasanayaka** [comment]
ND: Have a look at https://github.com/aswinnarayanan/recall2cache
